# Generated by Django 5.1.3 on 2025-01-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('sentiment', models.CharField(max_length=20)),
                ('solution', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerFeedback',
        ),
    ]
