# Generated by Django 5.1.3 on 2025-01-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_delete_customerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='feedback',
            name='keywords',
            field=models.TextField(default=0.0),
        ),
    ]
